### ISSUE TITLE
Any chance of Windows 10 Support?

### ISSUE THREAD

**Issue by RationalFragile** [tigros/HookTools#4]
Hi, I tried HookTools with Process Hacker 2.39 on Windows 10 64bit 21H1 and it shows "HookTools does not yet support this version of Windows!". Is there any chance you would be interested in adding support for Windows 10? It would be very useful for many people I assume. Thank you.

**Comment by tigros** [comment]
Hi, I did try years ago in vain. I think they changed the whole hook mechanism maybe alot maybe a little idk, would help to have windows 10 source code i suppose, otherwise it could be a waste of time even attempting it. someone who's expert in reverse engineering, assembler etc might be able to, just not my expertise. Thanks for asking tho.
Cheers.
